service: forex

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-2

functions:
  getLatest:
    handler: handler.getLatest
    memorySize: 512
    description: A simple Forex Rest API.
    events:
      - http: 
          path: api/forex
          method: get
          cors: true

